travis:
  secure:
    BINSTAR_TOKEN: FZKSpIHUgYudgqyBJLL7DU/fW8UH3G8t3gwtSAMFlvxtcJy8SGcsJwcJxCN2oRqRpq7Vtmo7NP/+BMI9buacYLEFE91rp48trCN4HlDU2cD3oOs241fpIdiXYrChZWm49GdzlqEZZj4Znj/MoT3Ny3QFt2MlTN2493hJLMLXrlYNf8vAh+x3xMkLM+IGH9yRExdQgdcBBiVdTt4q0C7xPmDOrvBafyKSTcGmBjZfJAaUpvul3U3zqaNtx3pSyEqWBGFuq/kywMc0VbnRT3XvMrtROt7xTknPPqpuGKxfBASQsnReqdZwS/tqSN20/6Yv9crc11p04aKvyW5GDLQdJ+m815sva2L50zTl5PV1n2v25YkiCZz+epUPJVa7Zb1YozDcMWHXIXtlf3JwdMeWqIxKSXv/PDD/5wqU74/IsgOyKLVKm1+rvdbcKWlWN04nUW4JueXyUe3HVgbGzmmrK4j3MP7HBnskgE3kD4QY2YxVStziXYJNhiLhJEFc0NuW5hwUyIQ1+I0N1o5DHzz1A1vBVNXR8mRLaRTKZ5kFaecZVj7LNYYOwQJMSZVWvIKc44LA0I/B5gcz0691ulI+7EOzpMDzjqVX39vrQW/UgSBauSIJ/PdG0E4HzchVymMrEtn52ATSJNLFqYmN/pxIz0iza5zrN3rHH4qOi0FldzE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
